version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: cards
      POSTGRES_PASSWORD: cards
      POSTGRES_DATABASE: cards
    ports:
      - '5432:5432'

  migrate:
    image: migrate/migrate
    command: -path=/migrations/ -database postgres://cards:cards@db/cards?sslmode=disable up 2
    volumes:
      - './migrations:/migrations'